name: tors-dists
channels:
- conda-forge
dependencies:
- python=3.10
- lenskit=0.14.2
- seedbank>=0.1.2
- pip
- psutil
- libblas=*=*openblas
- pandas>=1.5,<2
- scipy
- pyarrow
- tbb
- notebook
- jupytext
- quarto
- seaborn
- plotnine=0.12
- xarray
- joblib
- pymc >=5.4,<6
- docopt
- ipython
- ipywidgets
- tqdm
- statsmodels
- dvc>=2.54
- dvc-s3
- dvc-webdav
- pylatex
- conda-lock
